# Copyright 2026 AlphaOne LLC
# SPDX-License-Identifier: Apache-2.0
"""Webhook signature verification.

Wire contract (canonical source: ``src/subscriptions.rs:980-990``)
-----------------------------------------------------------------

When the ai-memory daemon delivers a subscription event it sends:

* ``X-AI-Memory-Signature: sha256=<hex>``
* ``X-AI-Memory-Timestamp: <unix-epoch-seconds>``
* ``X-AI-Memory-Correlation-Id: <uuid>``

The ``<hex>`` digest is::

    HMAC-SHA256(key = SHA256(plaintext_secret), msg = "{timestamp}.{body}")

Two details are load-bearing and BOTH were wrong in this SDK before #2455:

1. **The HMAC key is the SHA-256 DIGEST of the secret, not the secret.** The
   daemon stores ``secret_hash = sha256_hex(secret)`` at subscribe time and
   keys the HMAC on the hex-DECODED bytes of that hash — i.e. the raw 32-byte
   digest. Keying on the plaintext secret produces a completely different MAC.
2. **The signed message is ``"{timestamp}.{body}"``, not the bare body.** The
   timestamp is prefixed (with a literal ``.`` separator) so a captured
   signature is bound to the instant it was minted and cannot be replayed
   against a different delivery time.

Because the pre-#2455 implementation got both wrong,
:func:`verify_webhook_signature` could never return ``True`` for a genuine
delivery — every real webhook was rejected. The regression suite in
``tests/test_webhooks.py`` asserts against a fixture generated by the RUST signer
(``sdk/fixtures/webhook_hmac_vector.json``), not by this module, so the test
can never again agree with a wrong implementation.

Replay window
-------------

The timestamp is verified as well as consumed: a delivery whose timestamp is
older than ``max_age_secs`` (default 300s) or further in the future than
``max_skew_secs`` (default 60s) is rejected even when the MAC is valid. Those
bounds mirror the daemon's own inbound verifier
(``APPROVAL_HMAC_MAX_AGE_SECS`` / ``APPROVAL_HMAC_MAX_SKEW_SECS`` in
``src/handlers/approvals.rs``) and the AWS SigV4 / Stripe conventions.
"""

from __future__ import annotations

import hashlib
import hmac
import time

__all__ = [
    "DEFAULT_MAX_AGE_SECS",
    "DEFAULT_MAX_SKEW_SECS",
    "SIGNATURE_HEADER",
    "TIMESTAMP_HEADER",
    "sign_webhook_body",
    "verify_webhook_signature",
]

#: Header carrying ``sha256=<hex>``.
SIGNATURE_HEADER = "X-AI-Memory-Signature"
#: Header carrying the Unix-epoch-seconds timestamp that was signed.
TIMESTAMP_HEADER = "X-AI-Memory-Timestamp"

#: Maximum age of a delivery's timestamp before it is treated as a replay.
DEFAULT_MAX_AGE_SECS = 300
#: Maximum clock skew INTO THE FUTURE tolerated on a delivery's timestamp.
DEFAULT_MAX_SKEW_SECS = 60

_SIG_PREFIX = "sha256="


def _as_bytes(body: bytes | bytearray | memoryview | str) -> bytes:
    if isinstance(body, str):
        return body.encode("utf-8")
    return bytes(body)


def _canonical(timestamp: str, body: bytes) -> bytes:
    """The exact bytes the daemon signs: ``"{timestamp}.{body}"`` as UTF-8."""
    return timestamp.encode("utf-8") + b"." + body


def sign_webhook_body(
    body: bytes | bytearray | memoryview | str,
    secret: str,
    timestamp: str | int,
) -> str:
    """Produce the ``sha256=<hex>`` header value for ``body`` at ``timestamp``.

    Mirrors the daemon's signer exactly. Intended for local replay harnesses;
    production consumers only need :func:`verify_webhook_signature`.

    Note this function is deliberately NOT used to build the expected value in
    the conformance test — that would make the test tautological (the exact
    defect #2455 fixed). Tests assert against the Rust-generated fixture.

    Args:
        body: Raw body bytes (or a ``str``, encoded as UTF-8).
        secret: The plaintext subscription secret. It is SHA-256'd here — do
            not pre-hash it.
        timestamp: Unix epoch **seconds**. Rendered with ``str()``; pass the
            verbatim header value when reproducing a real delivery.

    Returns:
        ``"sha256=<64 hex chars>"``.
    """
    key = hashlib.sha256(secret.encode("utf-8")).digest()
    mac = hmac.new(key, _canonical(str(timestamp), _as_bytes(body)), hashlib.sha256)
    return f"{_SIG_PREFIX}{mac.hexdigest()}"


def verify_webhook_signature(
    body: bytes | bytearray | memoryview | str,
    signature: str,
    secret: str,
    *,
    timestamp: str | int,
    max_age_secs: int = DEFAULT_MAX_AGE_SECS,
    max_skew_secs: int = DEFAULT_MAX_SKEW_SECS,
    now: int | None = None,
) -> bool:
    """Verify an HMAC-SHA256 signature produced by the ai-memory daemon.

    Args:
        body: The raw request body bytes exactly as received (do **not**
            re-encode a parsed JSON payload; whitespace differences will
            break the HMAC).
        signature: The value of the ``X-AI-Memory-Signature`` header.
            Accepts either ``"sha256=<hex>"`` (the wire form) or a bare hex
            digest.
        secret: The plaintext shared secret configured when the subscription
            was created. Hashed internally — pass it as-is.
        timestamp: The value of the ``X-AI-Memory-Timestamp`` header. Fed
            VERBATIM into the signed message, so hand it the raw header
            string rather than a re-formatted integer. Keyword-only and
            **required**: a call site not updated for the #2455 wire contract
            raises ``TypeError`` loudly instead of silently verifying against
            the wrong construction.
        max_age_secs: Reject a delivery whose timestamp is older than this.
        max_skew_secs: Reject a delivery whose timestamp is further ahead of
            local time than this.
        now: Override for the current Unix time (seconds), for tests.

    Returns:
        ``True`` when the signature matches AND the timestamp is inside the
        replay window; ``False`` otherwise. Returns ``False`` — never raises
        — for malformed *delivery* input, so callers can treat any
        non-``True`` result as "reject this delivery."
    """
    if not signature or not isinstance(secret, str) or not secret:
        return False

    ts_raw = "" if timestamp is None else str(timestamp).strip()
    if not ts_raw:
        return False

    # Freshness first: a stale-but-authentic replay must be rejected, and
    # checking before the MAC compare avoids spending a hash on it.
    try:
        ts_value = int(ts_raw)
    except (TypeError, ValueError):
        return False
    current = int(time.time()) if now is None else int(now)
    age = current - ts_value
    if age > max_age_secs or -age > max_skew_secs:
        return False

    hex_sig = signature.strip().removeprefix(_SIG_PREFIX)

    try:
        received = bytes.fromhex(hex_sig)
    except ValueError:
        return False

    # key = SHA256(plaintext_secret) — the daemon stores that digest and keys
    # the HMAC on it, NOT on the plaintext secret. msg = "{ts}.{body}".
    key = hashlib.sha256(secret.encode("utf-8")).digest()
    mac = hmac.new(key, _canonical(ts_raw, _as_bytes(body)), hashlib.sha256).digest()
    return hmac.compare_digest(mac, received)
