-- v0.7.0 WT-1-D — `auto_atomise` namespace policy follow-up.
--
-- This migration is intentionally a documentation-only stamp; the
-- three new policy fields (`auto_atomise`, `auto_atomise_threshold_cl100k`,
-- `auto_atomise_max_atom_tokens`) live inside the namespace standard
-- memory's `metadata.governance` JSON blob, which is already a
-- nullable TEXT column on `memories`. No additional schema columns
-- are required — pre-WT-1-D rows simply omit the keys and the
-- substrate's `serde(default)` handling parses them as `None`,
-- which means "inherit / fall back to compiled default".
--
-- # Why this file exists
--
-- 1. **Versioning discipline.** The WT-1 epic deliberately bumps the
--    sqlite schema-version pointer at every WT-1-x landing so each
--    track gets a visible audit trail (`PRAGMA user_version`); a
--    follow-up that touches the namespace-policy surface gets its own
--    sequenced filename even when the work is purely additive on a
--    JSON column.
-- 2. **Replay safety.** The migrate ladder (in `src/storage/migrations.rs`)
--    bumps the schema-version probe past v36 to acknowledge that the
--    WT-1-D auto-atomisation policy is configured on this DB. The
--    ladder is idempotent — re-running this step is a no-op.
-- 3. **Documentation pin.** The WT-1-D brief promises a migration
--    number; reviewers and the cookbook walkthroughs cite this file
--    so the policy contract is grep-able from the migrations
--    directory.
--
-- # Field shapes
--
-- - `auto_atomise BOOL` (Option<bool>) — when `Some(true)`, the
--   substrate's `pre_store` hook deferred-enqueues a curator pass on
--   stored memories whose body exceeds the threshold.
-- - `auto_atomise_threshold_cl100k INTEGER` (Option<u32>) — cl100k_base
--   token threshold. Compiled default `500` when None / not set.
-- - `auto_atomise_max_atom_tokens INTEGER` (Option<u32>) — per-atom
--   token budget. Compiled default `200` when None / not set.
--
-- All three inherit leaf-first via `resolve_governance_policy` — a
-- child namespace that omits the field inherits the nearest
-- ancestor's explicit value.

-- No-op: the JSON column already exists on `memories.metadata` since
-- schema v7. This file is a stamp for the migrate ladder.
SELECT 1;
