-- v0.7.0 WT-1-D — `auto_atomise` namespace policy follow-up (postgres).
--
-- Mirrors `migrations/sqlite/0031_v07_namespace_auto_atomise.sql`. The
-- three new policy fields (`auto_atomise`, `auto_atomise_threshold_cl100k`,
-- `auto_atomise_max_atom_tokens`) live inside the namespace standard
-- memory's `metadata.governance` JSONB blob, which is already a
-- nullable JSONB column on `memories` since schema v12 (postgres).
-- No DDL is required — pre-WT-1-D rows simply omit the keys and the
-- substrate's `serde(default)` parses them as `None`.
--
-- # Field shapes
--
-- - `auto_atomise BOOL` (Option<bool>)
-- - `auto_atomise_threshold_cl100k INTEGER` (Option<u32>) — default 500
-- - `auto_atomise_max_atom_tokens INTEGER` (Option<u32>) — default 200
--
-- This file is a documentation stamp; the migrate ladder advances the
-- schema-version probe past v34 (postgres) to acknowledge that the
-- WT-1-D auto-atomisation policy is configured on this DB.

-- No-op: JSONB column already exists. Stamp for the migrate ladder.
SELECT 1;
