#!/usr/bin/env bash
# Copyright 2026 AlphaOne LLC
# SPDX-License-Identifier: Apache-2.0
#
# docker-1461 provision step 00 — seed the gitignored run dir.
#
# Idempotent. Creates the run-dir tree, mints the PG password secret
# (once), and renders two generated artifacts from the lib.sh SSOT:
#   - init-age.sql  : AGE + pgvector + per-peer schema bootstrap
#   - campaign.env  : the --env-file docker compose interpolates
#
# No literal topology/port/name/url value is written by hand: every
# field is derived from a lib.sh constant or an indexable helper, so a
# fork re-points the whole mesh by overriding the DOCKER_1461_* env
# vars before running — never by editing this script.
#
# Secret handling: the PG password is generated under `umask 077`,
# stored 0600, and never echoed. campaign.env (which embeds the
# password inside each peer's store URL) is likewise 0600 and lives in
# the gitignored run dir — never committed, never logged.

set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$SELF_DIR/lib.sh"

log "seed: run dir = $RUN_DIR"

# --------------------------------------------------------------------------
# 1. Run-dir tree (gitignored). Private subtrees get restrictive modes.
# --------------------------------------------------------------------------
umask 077
mkdir -p "$RUN_DIR" "$TLS_ROOT" "$ZT_ROOT" "$NODES_ROOT" "$SECRETS_DIR" "$REPORTS_DIR"
# Per-peer node trees that the compose bind-mounts into each container.
i=1
while [ "$i" -le "$PEER_COUNT" ]; do
  nd="$NODES_ROOT/$(peer_name "$i")"
  mkdir -p "$nd/tls" "$nd/keys" "$nd/trust"
  i=$((i + 1))
done
# PG container bind-mount tree (holds its CA-signed server cert/key).
mkdir -p "$PG_NODE_DIR/tls"

# --------------------------------------------------------------------------
# 2. PG password secret (minted once; reused on re-run for stable topology).
# --------------------------------------------------------------------------
if [ ! -s "$PG_PASSWORD_FILE" ]; then
  # 48 url-safe chars; no shell-special chars that would break the
  # postgres:// URL or the compose env-file parser. `head -c 48` closes
  # the pipe early, so `tr` (an unbounded /dev/urandom reader) takes
  # SIGPIPE — harmless, but it would trip `set -o pipefail`/`set -e`.
  # Generate inside a subshell with pipefail off so the early close
  # can't abort the script (bash-3.2-safe; cf. task #66 SIGPIPE class).
  pw="$(set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)"
  printf '%s' "$pw" >"$PG_PASSWORD_FILE"
  chmod 0600 "$PG_PASSWORD_FILE"
  log "seed: minted PG password ($PG_PASSWORD_FILE, 0600)"
else
  log "seed: reusing existing PG password"
fi

# --------------------------------------------------------------------------
# 3. Render init-age.sql from the lib.sh constants (graph, db, user, peer
#    schemas). AGE itself is auto-created by the base image before this
#    runs; pgvector is pinned to `public` so fresh SAL connections resolve
#    the `vector` type (their default search_path lacks ag_catalog).
# --------------------------------------------------------------------------
INIT_SQL="$RUN_DIR/init-age.sql"
{
  printf -- '-- GENERATED by provision/00_seed.sh from provision/lib.sh — DO NOT EDIT.\n'
  printf -- '-- Re-render: make seed (or run provision/00_seed.sh).\n\n'
  printf -- 'CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;\n\n'
  printf -- "LOAD 'age';\n"
  # "$user" is a literal PostgreSQL search_path keyword (per-role schema),
  # NOT a shell variable — it must reach the .sql file un-expanded.
  # shellcheck disable=SC2016
  printf -- 'SET search_path = ag_catalog, "$user", public;\n'
  printf -- "SELECT create_graph('%s');\n\n" "$AGE_GRAPH_NAME"
  # Per-peer search-path schemas.
  schemas=""
  i=1
  while [ "$i" -le "$PEER_COUNT" ]; do
    s="$(peer_schema "$i")"
    printf -- 'CREATE SCHEMA IF NOT EXISTS %s;\n' "$s"
    if [ -z "$schemas" ]; then schemas="$s"; else schemas="${schemas}, $s"; fi
    i=$((i + 1))
  done
  printf -- '\nGRANT ALL PRIVILEGES ON DATABASE %s TO %s;\n' "$PG_DB" "$PG_USER"
  printf -- 'GRANT ALL PRIVILEGES ON SCHEMA public, %s, ag_catalog TO %s;\n' "$schemas" "$PG_USER"
  printf -- 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ag_catalog TO %s;\n' "$PG_USER"
  printf -- 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ag_catalog TO %s;\n' "$PG_USER"
  printf -- 'GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ag_catalog TO %s;\n' "$PG_USER"
} >"$INIT_SQL"
chmod 0644 "$INIT_SQL"
log "seed: rendered $INIT_SQL"

# --------------------------------------------------------------------------
# 3b. Render pg_hba.conf — hostssl-ONLY client auth so every TCP connection
#     is refused PRE-AUTH unless it negotiated TLS (closes the daemon->PG
#     plaintext gap; this is the third encrypted leg of the mesh). The local
#     unix socket stays `trust` so initdb bootstrap, the `pg_isready`
#     healthcheck, and in-container psql probes work without a password.
# --------------------------------------------------------------------------
{
  printf -- '# GENERATED by provision/00_seed.sh from provision/lib.sh — DO NOT EDIT.\n'
  printf -- '# hostssl-ONLY: a non-TLS TCP connection is rejected pre-auth with\n'
  printf -- '# "no pg_hba.conf entry ... no encryption". Re-render: make seed.\n'
  printf -- '# TYPE     DATABASE  USER  ADDRESS      METHOD\n'
  printf -- 'local      all       all                trust\n'
  printf -- 'hostssl    all       all   0.0.0.0/0    scram-sha-256\n'
  printf -- 'hostssl    all       all   ::/0         scram-sha-256\n'
} >"$PG_HBA_FILE"
chmod 0644 "$PG_HBA_FILE"
log "seed: rendered $PG_HBA_FILE (hostssl-only)"

# --------------------------------------------------------------------------
# 4. Render campaign.env (the compose --env-file). 0600 because per-peer
#    store URLs embed the PG password. Values come straight from lib.sh.
# --------------------------------------------------------------------------
{
  printf '# GENERATED by provision/00_seed.sh — DO NOT EDIT, DO NOT COMMIT.\n'
  printf '# Mode 0600: per-peer store URLs embed the PG password.\n'
  printf 'COMPOSE_PROJECT=%s\n' "$COMPOSE_PROJECT"
  # --- images ---
  printf 'PG_IMAGE=%s\n' "$PG_AGE_VECTOR_IMAGE"
  printf 'DAEMON_IMAGE=%s\n' "$DAEMON_IMAGE"
  # --- postgres substrate ---
  printf 'PG_CONTAINER=%s\n' "$PG_CONTAINER"
  printf 'PG_HOSTNAME=%s\n' "$PG_HOSTNAME"
  printf 'PG_USER=%s\n' "$PG_USER"
  printf 'PG_PASSWORD=%s\n' "$(pg_password)"
  printf 'PG_DB=%s\n' "$PG_DB"
  printf 'PG_INTERNAL_PORT=%s\n' "$PG_INTERNAL_PORT"
  printf 'PG_PUBLISHED_PORT=%s\n' "$PG_PUBLISHED_PORT"
  printf 'PG_INIT_SQL=%s\n' "$INIT_SQL"
  printf 'PG_HBA_FILE=%s\n' "$PG_HBA_FILE"
  printf 'PG_NODE_DIR=%s\n' "$PG_NODE_DIR"
  # --- daemon wiring ---
  printf 'DAEMON_TIER=%s\n' "$DAEMON_TIER"
  printf 'CONTAINER_HTTPS_PORT=%s\n' "$CONTAINER_HTTPS_PORT"
  printf 'REMOTE_TLS_DIR=%s\n' "$REMOTE_TLS_DIR"
  printf 'REMOTE_KEY_DIR=%s\n' "$REMOTE_KEY_DIR"
  printf 'REMOTE_TRUST_DIR=%s\n' "$REMOTE_TRUST_DIR"
  printf 'REMOTE_CRED_PATH=%s\n' "$REMOTE_CRED_PATH"
  # --- federation / zero-touch ---
  printf 'FED_TRUST_DOMAIN=%s\n' "$FED_TRUST_DOMAIN"
  # --- AI NHI brain + embedder ---
  printf 'LLM_BACKEND=%s\n' "$LLM_BACKEND"
  printf 'LLM_MODEL=%s\n' "$LLM_MODEL"
  printf 'AUTO_TAG_MODEL=%s\n' "$AUTO_TAG_MODEL"
  printf 'EMBED_MODEL=%s\n' "$EMBED_MODEL"
  printf 'OLLAMA_BASE_URL=%s\n' "$OLLAMA_BASE_URL"
  # --- bridge network ---
  printf 'MESH_NETWORK=%s\n' "$MESH_NETWORK"
  printf 'MESH_SUBNET=%s\n' "$MESH_SUBNET"
  # --- per-peer (indexable) ---
  i=1
  while [ "$i" -le "$PEER_COUNT" ]; do
    printf 'PEER%s_NAME=%s\n'            "$i" "$(peer_name "$i")"
    printf 'PEER%s_AGENT_ID=%s\n'        "$i" "$(peer_agent_id "$i")"
    printf 'PEER%s_FED_ID=%s\n'          "$i" "$(peer_fed_id "$i")"
    printf 'PEER%s_PUBLISHED_PORT=%s\n'  "$i" "$(peer_port "$i")"
    printf 'PEER%s_PEER_URLS=%s\n'       "$i" "$(peer_quorum_urls "$i")"
    printf 'PEER%s_STORE_URL=%s\n'       "$i" "$(store_url_for_schema "$(peer_schema "$i")")"
    printf 'PEER%s_NODE_DIR=%s\n'        "$i" "$NODES_ROOT/$(peer_name "$i")"
    i=$((i + 1))
  done
} >"$COMPOSE_ENV_FILE"
chmod 0600 "$COMPOSE_ENV_FILE"
log "seed: rendered $COMPOSE_ENV_FILE (0600)"

log "seed: OK — $PEER_COUNT peers, PG=$PG_CONTAINER, net=$MESH_NETWORK ($MESH_SUBNET)"
